accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout')
]

articles/urls.py
from django.urls import path

from . import views


app_name='articles'
urlpatterns = [
    path('', views.article_list, name='list'),
    path('article_create/', views.article_create, name='create'),
    path('article_drafts/', views.article_drafts, name='drafts'),
    path('article_edit/<int:pk>', views.article_edit, name='edit'),
    path('article_detail/<slug:slug>/<int:pk>', views.article_details, name='details'),
    path('article_like/<int:article_id>', views.like, name='like'),
    path('article_search/', views.article_search, name='search'),
    path('delete/<int:pk>', views.article_delete, name='delete'),
]

catron/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.article_list, name='home')
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['title']

    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField("Title", max_length=250)
    slug = models.SlugField()
    body = models.TextField()
    thumb = models.ImageField(null=True)
    category = models.ManyToManyField(Category, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(null=True, blank=True, verbose_name="Published date")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def snippet(self):
        return self.body[:100] + '...'

    def publish(self):
        self.published_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    @property
    def like_count(self):
        return Like.objects.filter(article=self).count()



class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields  = ['title', 'slug', 'body', 'thumb', 'category']
		widgets = {
		'category': forms.CheckboxSelectMultiple
		}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})



def logout_view(request):
    logout(request)
    return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
import time


from asgiref.sync import sync_to_async
#models
from .models import Article
from .models import Category
from .models import Like



# Create your views here.

def article_list(request):
    articles = Article.objects.filter(published_at__isnull=False).order_by('created_at')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_search(request):
    search_query = request.GET['search']
    results = Article.objects.filter(title__contains=search_query)
    return render(request, 'articles/article_list.html', {'articles': results})


@login_required()
def article_drafts(request):
    drafts = Article.objects.filter(published_at__isnull=True)
    return render(request, 'articles/article_list.html', {'articles': drafts})


def save_instance(title):
    instance = Category(title=title)
    instance.save()
    return instance

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user


            print(instance)
            saved_new_cats = []
            

            if 'save_draft' in request.POST: 
                instance.save()

            elif 'publish_now' in request.POST:
                print(request.POST)
                instance.publish()

            else:
                return HttpResponse('Something went wrong')
              

            if request.POST.get('category', False):
                instance.category.add(request.POST['category'])


            if 'new-category' in request.POST:
                # new_categories = [Category(title=cat) for cat in request.POST.getlist('new-category')]
                print(request.POST.getlist('new-category')) 
                
                for cat in request.POST.getlist('new-category'):
                    saved = sync_to_async(save_instance(cat), thread_sensitive=True)
                    print(saved.id, "this")
                    instance.category.add(saved.id)
            # if len(saved_new_cats)!=0:
            #     print("Performing adding new categories")
            #     for c in saved_new_cats: print('Prining ids', c.id)
            # else:
            #     print("Sorry")
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

    

@login_required(login_url="/accounts/login/")
def article_edit(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            form = forms.CreateArticle(request.POST, request.FILES, instance=article)
            form.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle(instance=article)
    return render(request, 'articles/article_edit.html', {'form': form})

@login_required(login_url="/accounts/login/")
def article_delete(request, pk):
    if request.method == "POST":
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect('articles:list')
    else:
        return redirect('articles:list')


@login_required(login_url="/accounts/login/")
def article_details(request, slug, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'articles/article_details.html', {'article': article})

@login_required()
def like(request, article_id):
    new_like, created = Like.objects.get_or_create(user=request.user, article_id=article_id)
    if not created:
        new_like.delete()
    return redirect('articles:list')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
<!-- {% load crispy_forms_tags %} -->
{% block content %}
	<div class="container">
		<div class="row justify-content-center m-4">
			<div class="col-12 col-sm-12 col-md-6 col-lg-4 border rounded p-4">

				<h3>Login</h3>
				<form class="site-form" action="{% url 'accounts:login' %}" method="post">
					{% csrf_token %}
					{{form}}
					{% if request.GET.next %}
						<input type="hidden" name="next" value="{{request.GET.next}}" >
					{% endif %}
					<input type="submit" class="btn btn-light " value="Login">
					<a class="ml-auto" href="{% url 'accounts:signup' %}" >Sign up instead</a>
				</form>
			</div>
		</div>
	</div>
	
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

<!-- {% load crispy_forms_tags %} -->

{% block content %}
<div class="container">
		<div class="row justify-content-center m-4">
			<div class="col-12 col-sm-12 col-md-6 col-lg-4 border rounded p-4">

				<h3 class="mx-auto">Sign up</h3>
				<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
					{% csrf_token %}
					{{form}}
					{% if request.GET.next %}
						<input type="hidden" name="next" value="{{request.GET.next}}" >
					{% endif %}
					<input type="submit" class="btn btn-light d-flex" value="Sign up">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto my-4 p-5" style='max-width: 700px'>
        <h1>Create article</h1>
        <form action="{% url 'articles:create' %}"  method="post" enctype="multipart/form-data" id="create-article-form">
            {%csrf_token%}
            {{form|crispy}}

             <a class="d-flex mr-auto my-2"  data-toggle="collapse" id="add-category-btn" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                Add new category
            </a>
            <div class="collapse" id="collapseExample">
                <div>
                   <input type="text" id="category-to-add" class="p-1">
                   <span class="btn btn-success" id="add-category">Add</span>
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <input type="submit" name="save_draft" class="btn btn-primary mr-2" value="Save draft">
                <input type="submit" name="publish_now" class="btn btn-success" value="Publish now">
            </div>

            </form>
        </div>
    {% endblock %}

articles/templates/articles/article_details.html
{% extends 'base.html'%}

{%block content%}
    <div class="card mx-auto p-2 mt-1" style="width:95%">

        <h2>{{article.title}}</h2>

        <img src="{{article.thumb.url}}" alt="">
        <p >{{article.body}}</p>

        <p>Written by {{ article.author.username }}</p>
        <p>{{article.date}}</p>

      {% if article.author.id == user.id %}
        <form action="{% url 'articles:delete' article.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Delete">
        </form>

        <a href="{% url 'articles:edit' pk=article.id %}">Edit</a>
      {% endif %}

      </div>
{%endblock%}

articles/templates/articles/article_edit.html
{% extends 'base.html'%}
<!-- {% load crispy_forms_tags %} -->

{%block content%}

    <div class="create-article">
        <h1>Edit article</h1>

        <form action="{% url 'articles:edit' article.id%}" class="site-form" method="post" enctype="multipart/form-data">
          {%csrf_token%}
          {{form}}
          <div class="d-flex justify-content-end">
            <input type="submit" class="btn btn-primary mr-2" value="Publish changes">
          </div>
        </form>
    </div>
{%endblock%}

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container mt-5">
    <div class="row">
      
      {% for article in articles %}
        <div class="col col-12 col-md-4 col-lg-4">
          <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="https://images.unsplash.com/photo-1608824612748-cbdb1838802c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title ">
              <a href="{% url 'articles:details' slug=article.slug pk=article.id %}" class="text-dark">{{article}}</a>
              </h5>
              <h6 class="card-subtitle mb-2 text-muted">{{article.published_at}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">By {{article.author}}</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p class="card-subtitle mb-2 text-muted">Categories:
                {% for category in article.category.all %}
                  {{category}}
                {% endfor %}
              </p>
              <a href="{% url 'articles:details' slug=article.slug pk=article.id %}" class="btn btn-primary">Learn more</a>
              <a href="{% url 'articles:like' article.id %}" class="ml-5 text-danger">
                <i class="fa fa-heart red"></i>
              </a>
              <span>{{article.like_count}} likes</span>
            </div>
          </div>
        </div>
        <!-- <div class="card mx-auto my-2" style="max-width:90%">
          <div class="card-body">
            <h3 class="card-title"><a href="{% url 'articles:details' slug=article.slug pk=article.id %}" class="title">{{article}}</a></h3>
            <p class="card-subtitle mb-2 text-muted">Categories:
              {% for category in article.category.all %}
                #{{category}}
              {% endfor %}
            </p>
            <p class="card-text">{{article.snippet}}</p>
            <a href="{% url 'articles:like' article.id %}">
              <i class="fa fa-heart red"></i>
            </a>
            <p>{{article.like_count}} {{article.created_at}} {{article.published_at}}</p>
          </div>
        </div> -->
      {% endfor %}
      
    </div>
  </div>
  
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Articles</title>
    <meta name="description" content="The HTML5 Herald">
    <meta name="author" content="SitePoint">
    <link rel="stylesheet" href="{% static 'style.css'%}">

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'articles:list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:create' %}">Create Article</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'articles:drafts' %}" tabindex="-1" aria-disabled="true">Drafts</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex ml-lg-auto">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
        {% if user.is_authenticated %}
          <div class="dropdown ml-2">
            <button class="btn btn-secondary rounded-circle " type="button" id="dropdownMenuButton" data-toggle="dropdown" >
            {{user|make_list|first}}
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">My Profile</a>
              <a class="dropdown-item" href="#">Logout</a>
              <a class="dropdown-item" href="#">Upgrade to PRO</a>
            </div>
          </div>
          {% else %}
          <a href="{% url 'accounts:login' %}" class="btn ">Sign In</a>
          <a href="{% url 'accounts:signup' %}" class="btn text-success">Sign Up</a>
        {% endif %}
      </div>
    </nav>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
    
    <script type="text/javascript" src="{% static 'catron_script.js'%}"></script>
  </body>
</html>